name: Caesar Cipher C CI
on:
  push:
    branches: [ main, ulepszone_szablony ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang-tidy clang-format
      - name: Configure CMake
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: cd build && ctest --output-on-failure
      - name: Lint
        run: clang-tidy src/*.c
      - name: Format
        run: clang-format --dry-run --Werror src/*.c
