name: Unit Test C Projects
on:
  push:
    branches: [ main, ulepszone_szablony ]
  pull_request:
    branches: [ main ]
jobs:
  test-c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: List all C projects
        id: list
        run: |
          PROJECTS=$(ls -1 src/c | xargs)
          echo "projects=$PROJECTS" >> $GITHUB_OUTPUT
      - name: Run tests for all C projects
        run: |
          set -x
          ls -l src/c
          for proj in ${{ steps.list.outputs.projects }}; do
            echo "Testuję projekt: $proj"
            if [ ! -d src/c/$proj ]; then
              echo "Directory src/c/$proj does not exist!"
              exit 1
            fi
            cd src/c/$proj
            cmake -S . -B build
            cmake --build build
            cd build && ctest --output-on-failure || exit 1
            cd ../../..
          done
