name: Unit Test C Projects
on:
  push:
    branches: [ main, ulepszone_szablony ]
  pull_request:
    branches: [ main ]
jobs:
  test-c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang-tidy clang-format
      - name: Make test script executable
        run: chmod +x scripts/test-all-c-projects.sh
      - name: Run all C project tests
        run: ./scripts/test-all-c-projects.sh
